name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install build + test deps
        run: |
          python -m pip install --upgrade pip
          pip install -U build pytest pytest-cov flake8

      - name: Install package (editable)
        run: |
          pip install -e .

      - name: Lint (fail on errors)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=databoi --cov-report=xml

      - name: Smoke import
        run: |
          python - <<'PY'
          import databoi
          print("databoi version:", getattr(databoi, "__version__", "n/a"))
          PY
